# Site settings
title: Django Versions
description: > # this means to ignore newlines until "baseurl:"
  django-community-versions provides helpful badges with versioning
  information to community resources, like blog posts.
baseurl: "/django-community-versions"
# url: "http://vanjacosic.github.io"

# Build settings
markdown: kramdown
